#pragma once

#include "DSPInterfaces.h"
#include <algorithm>
#include <cstdint>

class ADC12Bit : public Converter
{
public:
    float process(float sample) override
    {
        return static_cast<float>(quantize(applyInputSaturation(sample)));
    }

    int16_t quantize(float sample)
    {
        // 12-bit range is -2048 to 2047
        float scaled = sample * 2047.0f;
        int32_t quantized = static_cast<int32_t>(scaled);
        return static_cast<int16_t>(std::clamp(quantized, -2048, 2047));
    }

    float applyInputSaturation(float sample)
    {
        // ADC hard clipping
        return std::clamp(sample, -1.0f, 1.0f);
    }
};

class DAC12Bit : public Converter
{
public:
    float process(float sample) override
    {
        // The sample coming from memory is essentially an int16_t stored as float, or generated by the loop memory
        return reconstruct(static_cast<int16_t>(sample));
    }

    float reconstruct(int16_t sample)
    {
        return static_cast<float>(sample) / 2047.0f;
    }
};
